### ISSUE TITLE
make ssh connection in web UI

### ISSUE THREAD

**Issue by Drinkey** [emre/storm#101]
Is it possible that we can make SSH connection straight to target right in WebUI? It'll be very handy feature. Current storm web UI only support add and edit connection.

**Comment by emre** [comment]
didn't really get what do you mean? can you explain further?

**Comment by Drinkey** [comment]
sorry for the confusing. When start a web server with 'storm web', we can see stored ssh sessions listed in web UI, but we cannot initiate SSH from WebUI. If we can do that, it could make us manage ssh session more efficiently with visibility.

**Comment by emre** [comment]
initating it from the web ui is tricky. that can be an extension-plugin like thing. but I don't think it will be in core of stormssh.

thanks for the idea but closing this.
