### ISSUE TITLE
id_file param: add file should use abspath

### ISSUE THREAD

**Issue by brenol** [emre/storm#102]
Hi!

I was using storm ssh and ran the following command:
`storm add --id_file mykey.key myserver myserverip`

However, I noticed that upon changing directory I was having a issue:
`file mykey.key not found`

Shouldn't adding a key use path lib? Example:
```
import path

path_to_key = path.Path(id_file).abspath()
```

The problem with the approach above is that it does not follow directories (i.e. running it on /home/myuser/test and to use a key in ~/Downloads)

Implementation can be improved obviously, but I think this would be a nice addition to such a wonderful tool.

**Comment by emre** [comment]
> The problem with the approach above is that it does not follow directories (i.e. running it on 
> /home/myuser/test and to use a key in ~/Downloads)

not sure if I understand it right, you can use /home/user/Downloads/foo.key as an argument. can you detail the problem a little bit more?

**Comment by brenol** [comment]
I meant that if your key is in a place like:
`/home/myuser/test/world`

And you pass `~/keys/adserver-key` as a parameter, `path.Path` will not expand it in the middle and the path will be there.

However, this is just a issue with the approach I posted.

I thought this further and I don't think the library needs this, although it would be nice and would make a few things easier, it simply is not the point of the library.
