### ISSUE TITLE
Add dry-run option when adding an entry

### ISSUE THREAD

**Issue by grayaii** [emre/storm#113]
It would be really cool if there was a way to write to stdout what the entry you are about to add to your ssh config file.

Something like this:
`storm add my_vps root@emreyilmaz.me:22 --dry-run`

```
Host my_vps
    hostname emreyilmaz.me
    user root
    port 22
```

Technically, I could do something like this:
storm add my_vps root@emreyilmaz.me:22 --config /tmp/foo.config

And then cat out /tmp/foo.config

But it would be cool if this tool did that :)

**Comment by emre** [comment]
hmm, sounds like a good idea. that's a todo. thanks for the idea.

**Comment by emre** [comment]
That was a PR about this but I didn't like the solution and the complexity behind it. I don't see much +1s to that PR, so I am closing it.

If there will be a better demand, we can revisit this later on. Thanks for the idea.
