### ISSUE TITLE
Grouping Configurations

### ISSUE THREAD

**Issue by molovo** [emre/storm#114]
Hi. I really like Storm's CLI interface as a nice easy wrapper for SSH config. I was wondering if there was any feasibility for adding groups to storm's output. I currently have 60+ hosts defined in my config file, grouped using comments, but obviously this information isn't transferred to Storm's output. I appreciate this might not be an easy thing to add, just wondering if you thought it was feasible (and possibly worth pursuing with a pull request, as I'm not a Python guy... yet)?

**Comment by emre** [comment]
It doesn't look easy in the first glance. 

I will make a couple of experiments about this, meanwhile can you post an example ssh config to play with? (don't forget to remove any sensitive information :innocent:)
