### ISSUE TITLE
Add host with keyfile on web-ui

### ISSUE THREAD

**Issue by SharkIng** [emre/storm#120]
I know how to do it with command line interface but seem not working on Web UI

**Comment by emre** [comment]
web ui -somewhat- unmaintained at this time. any pull requests appreciated. 

/cc @f @berkerpeksag

**Comment by f** [comment]
I just checked how it's being sent from Web UI.

```
{name: "user_at_host", connection_uri: "user@host --test --argument"}
```

This is the payload. 

I wonder if keyfile is `id_file`. In `web.py` it checks payload for the `id_file` key and adds it with this parameter. We can add `id_file` request from Web UI.

**Comment by emre** [comment]
@f,

yes, keyfile is id_file.

**Comment by f** [comment]
Here is the Pull Request I added the support of `id_file`: https://github.com/emre/storm/pull/121

It looks like this:

![Image](https://dl.dropboxusercontent.com/s/8mb47sl13i0vsja/Screenshot%202016-05-04%2020.14.32.png)

**Comment by emre** [comment]
thanks!

I will close this when I release a new version.

**Comment by f** [comment]
I'll make some improvements, please wait for them before new version.

**Comment by SharkIng** [comment]
Thanks @f and Thanks @emre  for this awesome idea/software

**Comment by f** [comment]
@SharkIng Thanks to @emre for this awesome project, I'm just the maintainer of web part :) Additionally we add two themes for the web ui: https://github.com/emre/storm/pull/122 \o/

**Comment by emre** [comment]
this is on air w/ 0.6.9. update your stormssh 👍
