### ISSUE TITLE
Add/edit identity file through web interface

### ISSUE THREAD

**Issue by 6farer** [emre/storm#125]
Improvement

**Comment by emre** [comment]
can you expand a bit? ssh keys? adding/editing them?

**Comment by 6farer** [comment]
Sorry. I meant identity file path. I updated the title.

**Comment by emre** [comment]
It should be possible with the new release. can you update it and try again?

**Comment by 6farer** [comment]
I see. Can you update the version on brew?
[https://github.com/Homebrew/homebrew-core/blob/master/Formula/stormssh.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/stormssh.rb)

**Comment by emre** [comment]
@youtux, I belive you maintain the homebrew package of stormssh. Can you update it? Relevant tag: **0.6.9**

If that's not the case, sorry for pinging you :)

**Comment by youtux** [comment]
@emre Sorry for the late response, I will be happy to update it, if nobody already did it.

**Comment by emre** [comment]
thanks 🤗

**Comment by youtux** [comment]
See https://github.com/Homebrew/homebrew-core/pull/3394

**Comment by emre** [comment]
thank you! :)
