### ISSUE TITLE
on ubuntu16.04 python3.5 error

### ISSUE THREAD

**Issue by liupeng0518** [emre/storm#127]
Collecting storm
  Downloading https://pypi.doubanio.com/packages/a7/4c/e5dbc818c432cd80d2e1aa1576f911eda49a3c206c6697db4070f402cda9/storm-0.20.tar.bz2 (213kB)
    100% |████████████████████████████████| 215kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_w32z0zy/storm/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-_w32z0zy/storm/ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_w32z0zy/storm/

**Comment by emre** [comment]
use **stormssh** as package name instead of storm.
