### ISSUE TITLE
id_file is mandatory when we edit an entry in web ui

### ISSUE THREAD

**Issue by k-aclyon** [emre/storm#129]
hello!
thank you for this very useful tool !
i noticed that we are unable to edit an entry with the web ui without specifying an id_file
is there a way to make id_file as an option ?
(sorry for my english)
thank you.

**Comment by reorx** [comment]
I also encountered this problem and tried to fix it in PR #135 , you can use [my fork](https://github.com/reorx/storm/tree/fix-del-keyerror) before the author fix this officially

**Comment by emre** [comment]
Hi,

Thanks for filing a ticket about the issue, but we just decided to remove storm-web from storm codebase therefore it will be no longer supported.
