### ISSUE TITLE
Still no password management?

### ISSUE THREAD

**Issue by jagoff** [emre/storm#134]
Tool is great, but, still no password management? is upset put password every time. 

Nice work btw!

**Comment by emre** [comment]
There is no plan to support this kind of thing.

You can use ssh key authentication instead of passwords.

https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server

Thanks.

**Comment by jagoff** [comment]
Thanks.
