### ISSUE TITLE
Feature request: Cloud Sync

### ISSUE THREAD

**Issue by jagoff** [emre/storm#155]
I think if storm will have a cloud sync for replicate the configuration (ssh servers) from "everywhere" would be nice.

I can try to help with this feature. 

What do you think?

**Comment by denzuko** [comment]
I've thought about this as well and been working on a way in my PR to have ssh storm running on the remote node so ansible or the ssh storm cli could control remote configurations. Though a good _pure ssh_ way to "replicate" would be via a cronjob that updates with git, rsync, or the ansible copy module.

**Comment by RogerSik** [comment]
Where are the configuration files stored?

**Comment by RogerSik** [comment]
Found out that stormssh is saving the config under ~/.ssh/config

**Comment by emre** [comment]
This should be done via external tools. No exactly this project's focus.
