### ISSUE TITLE
Tag the most recent release and push to https://pypi.org/

### ISSUE THREAD

**Issue by philwrenn** [emre/storm#163]
It would be nice to have some of strom's more recent updates available when installed with pip.

**Comment by gregorynicholas** [comment]
hi @philwrenn, happy to help.  what in particular can i do?

**Comment by philwrenn** [comment]
Hi @gregorynicholas, Are you possibly the person that own this? https://pypi.org/project/ssh-storm/
I was hoping we could get some of the projects more recent update in PyPI.

**Comment by gregorynicholas** [comment]
got it.  yes that was me that pushed that up to pypi. i can update my fork & upload the latest version to the package index.

**Comment by emre** [comment]
Recent updates are already available at pip. (v0.7.0) for a couple of weeks. Also tagged the version, now.

**Comment by emre** [comment]
@philwrenn please, feel free to close the issue once you confirm that you can install the latest version from pypi.

**Comment by philwrenn** [comment]
`pip search` is still returning `ssh-storm (0.3.5)`. The PyPI web interface is also showing 0.3.5 - https://pypi.org/project/ssh-storm/

@emre Do you have the project in the PyPI under a different name?

**Comment by emre** [comment]
@philwrenn project name on pypi is: stormssh. ssh-storm looks like a fork.
