### ISSUE TITLE
Tag releases on the git repository

### ISSUE THREAD

**Issue by youtux** [emre/storm#95]
Hello @emre, first of all I want to thank you for this amazing tool.

I would like to ask you to tag every release in the git repository, such that one can easily checkout the latest available version using git. This is useful also for my script [brew-livecheck](https://github.com/youtux/homebrew-livecheck) to check if there is an update version of your application.

**Comment by emre** [comment]
thanks.

no problem, let's tag the newer versions then.

**Comment by youtux** [comment]
👍
